<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class CreateSeoMetadataTable extends Migration
{
    public function up()
    {
        $this->forge->addField([
            'id' => [
                'type'           => 'INT',
                'constraint'     => 11,
                'unsigned'       => true,
                'auto_increment' => true,
            ],
            'page_key' => [
                'type'       => 'VARCHAR',
                'constraint' => '100',
            ],
            'page_name' => [
                'type'       => 'VARCHAR',
                'constraint' => '255',
            ],
            'seo_title' => [
                'type'       => 'VARCHAR',
                'constraint' => '255',
                'null'       => true,
            ],
            'meta_description' => [
                'type' => 'TEXT',
                'null' => true,
            ],
            'meta_keywords' => [
                'type' => 'TEXT',
                'null' => true,
            ],
            'canonical_url' => [
                'type'       => 'VARCHAR',
                'constraint' => '500',
                'null'       => true,
            ],
            'og_title' => [
                'type'       => 'VARCHAR',
                'constraint' => '255',
                'null'       => true,
            ],
            'og_description' => [
                'type' => 'TEXT',
                'null' => true,
            ],
            'og_image' => [
                'type'       => 'VARCHAR',
                'constraint' => '500',
                'null'       => true,
            ],
            'robots' => [
                'type'       => 'VARCHAR',
                'constraint' => '100',
                'default'    => 'index, follow',
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'null' => true,
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'null' => true,
            ],
        ]);

        $this->forge->addKey('id', true);
        $this->forge->addUniqueKey('page_key');
        $this->forge->createTable('seo_metadata', true);

        // Prepopulate with all existing and core public pages
        $db = \Config\Database::connect();
        $now = date('Y-m-d H:i:s');
        $initialPages = [
            [
                'page_key'         => 'home',
                'page_name'        => 'Homepage',
                'seo_title'        => 'Glowup Beauty Studio & Academy | Luxury Wellness & Haircare',
                'meta_description' => 'Premium beauty treatments, clinical facials, and transformative hair alchemy curated within an architectural academy of stillness in Madurai.',
                'meta_keywords'    => 'beauty studio, luxury salon, haircare, facial, aesthetics, bridal makeover, Madurai',
                'canonical_url'    => '',
                'og_title'         => 'Glowup Beauty Studio & Academy | Luxury Wellness & Haircare',
                'og_description'   => 'Premium beauty treatments, clinical facials, and transformative hair alchemy curated within an architectural academy of stillness.',
                'og_image'         => 'assets/images/Glowup_Logo_Black_White.png',
                'robots'           => 'index, follow',
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'page_key'         => 'about',
                'page_name'        => 'About Us',
                'seo_title'        => 'About Us | Glowup Beauty Studio & Academy',
                'meta_description' => 'Discover the philosophy, artistry, and vision behind Glowup Beauty Studio & Academy in Madurai.',
                'meta_keywords'    => 'about glowup, beauty academy team, aesthetic directors, bridal stylists',
                'canonical_url'    => '',
                'og_title'         => 'About Us | Glowup Beauty Studio & Academy',
                'og_description'   => 'Discover the philosophy, artistry, and vision behind Glowup Beauty Studio & Academy in Madurai.',
                'og_image'         => 'assets/images/Glowup_Logo_Black_White.png',
                'robots'           => 'index, follow',
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'page_key'         => 'services',
                'page_name'        => 'Services & Treatments',
                'seo_title'        => 'Treatment Menu & Services | Glowup Beauty Studio & Academy',
                'meta_description' => 'Explore our bespoke menu of restorative facials, master hair therapies, and transformative beauty rituals.',
                'meta_keywords'    => 'salon services, aesthetic facials, hair alchemy, keratin, hydrafacial, bridal couture',
                'canonical_url'    => '',
                'og_title'         => 'Treatment Menu & Services | Glowup Beauty Studio & Academy',
                'og_description'   => 'Explore our bespoke menu of restorative facials, master hair therapies, and transformative beauty rituals.',
                'og_image'         => 'assets/images/Glowup_Logo_Black_White.png',
                'robots'           => 'index, follow',
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'page_key'         => 'academy',
                'page_name'        => 'Academy & Courses',
                'seo_title'        => 'Academy of Beauty Arts & Courses | Glowup',
                'meta_description' => 'Professional beauty education, masterclasses, and certified courses in cosmetology, hair design, and aesthetic artistry.',
                'meta_keywords'    => 'beauty academy, cosmetology course, hair styling diploma, makeup certification, Madurai',
                'canonical_url'    => '',
                'og_title'         => 'Academy of Beauty Arts & Courses | Glowup',
                'og_description'   => 'Professional beauty education, masterclasses, and certified courses in cosmetology, hair design, and aesthetic artistry.',
                'og_image'         => 'assets/images/Glowup_Logo_Black_White.png',
                'robots'           => 'index, follow',
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'page_key'         => 'bridal',
                'page_name'        => 'Bridal Packages',
                'seo_title'        => 'Bridal Couture Packages & Makeover Tiers | Glowup',
                'meta_description' => 'Signature bridal packages, destination bridal transformations, and bespoke pre-wedding rituals crafted for your radiance.',
                'meta_keywords'    => 'bridal makeup, bridal package, wedding makeover, bridal jewelry styling',
                'canonical_url'    => '',
                'og_title'         => 'Bridal Couture Packages & Makeover Tiers | Glowup',
                'og_description'   => 'Signature bridal packages, destination bridal transformations, and bespoke pre-wedding rituals crafted for your radiance.',
                'og_image'         => 'assets/images/Glowup_Logo_Black_White.png',
                'robots'           => 'index, follow',
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'page_key'         => 'rentals',
                'page_name'        => 'Rentals & Jewellery',
                'seo_title'        => 'Luxury Jewellery & Costume Rentals | Glowup',
                'meta_description' => 'Exquisite bridal jewellery sets, costume ornaments, and premium designer accessories available for bespoke hire.',
                'meta_keywords'    => 'bridal jewellery rental, temple jewelry hire, photoshoot costume rental',
                'canonical_url'    => '',
                'og_title'         => 'Luxury Jewellery & Costume Rentals | Glowup',
                'og_description'   => 'Exquisite bridal jewellery sets, costume ornaments, and premium designer accessories available for bespoke hire.',
                'og_image'         => 'assets/images/Glowup_Logo_Black_White.png',
                'robots'           => 'index, follow',
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'page_key'         => 'photoshoot',
                'page_name'        => 'Photoshoot Sessions',
                'seo_title'        => 'Editorial Photoshoot Sessions & Styling | Glowup',
                'meta_description' => 'High-fashion editorial photoshoot sessions, portfolio shoots, and specialized bridal styling in our studio.',
                'meta_keywords'    => 'photoshoot studio, model portfolio, bridal photoshoot, editorial styling',
                'canonical_url'    => '',
                'og_title'         => 'Editorial Photoshoot Sessions & Styling | Glowup',
                'og_description'   => 'High-fashion editorial photoshoot sessions, portfolio shoots, and specialized bridal styling in our studio.',
                'og_image'         => 'assets/images/Glowup_Logo_Black_White.png',
                'robots'           => 'index, follow',
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'page_key'         => 'events',
                'page_name'        => 'Studio Events & Workshops',
                'seo_title'        => 'Masterclasses & Studio Events | Glowup Academy',
                'meta_description' => 'Upcoming masterclasses, seasonal beauty workshops, and exclusive artistic gatherings at Glowup Studio.',
                'meta_keywords'    => 'beauty workshops, makeup masterclass, styling seminars',
                'canonical_url'    => '',
                'og_title'         => 'Masterclasses & Studio Events | Glowup Academy',
                'og_description'   => 'Upcoming masterclasses, seasonal beauty workshops, and exclusive artistic gatherings at Glowup Studio.',
                'og_image'         => 'assets/images/Glowup_Logo_Black_White.png',
                'robots'           => 'index, follow',
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'page_key'         => 'gallery',
                'page_name'        => 'Visual Gallery & Lookbook',
                'seo_title'        => 'Gallery & Portfolio | Glowup Beauty Studio & Academy',
                'meta_description' => 'A visual curated anthology of haute couture hair artistry, transformative skin therapies, and editorial craftsmanship.',
                'meta_keywords'    => 'beauty studio portfolio, lookbook, hair transformations, before and after',
                'canonical_url'    => '',
                'og_title'         => 'Gallery & Portfolio | Glowup Beauty Studio & Academy',
                'og_description'   => 'A visual curated anthology of haute couture hair artistry, transformative skin therapies, and editorial craftsmanship.',
                'og_image'         => 'assets/images/Glowup_Logo_Black_White.png',
                'robots'           => 'index, follow',
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'page_key'         => 'reviews',
                'page_name'        => 'Patron Reviews & Testimonials',
                'seo_title'        => 'Patron Reviews & Testimonials | Glowup Beauty Studio & Academy',
                'meta_description' => 'Read verified client testimonials and patron reviews of Glowup Beauty Studio & Academy luxury hair, skin, and wellness rituals.',
                'meta_keywords'    => 'client reviews, salon testimonials, customer feedback, verified reviews',
                'canonical_url'    => '',
                'og_title'         => 'Patron Reviews & Testimonials | Glowup Beauty Studio & Academy',
                'og_description'   => 'Read verified client testimonials and patron reviews of Glowup Beauty Studio & Academy luxury hair, skin, and wellness rituals.',
                'og_image'         => 'assets/images/Glowup_Logo_Black_White.png',
                'robots'           => 'index, follow',
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'page_key'         => 'blog',
                'page_name'        => 'Editorial Journal & Blog',
                'seo_title'        => 'Beauty Journal & Editorial Articles | Glowup',
                'meta_description' => 'Insightful beauty reflections, aesthetic trends, haircare science, and bridal guidance from Glowup masters.',
                'meta_keywords'    => 'beauty blog, skincare tips, hair care trends, bridal advice',
                'canonical_url'    => '',
                'og_title'         => 'Beauty Journal & Editorial Articles | Glowup',
                'og_description'   => 'Insightful beauty reflections, aesthetic trends, haircare science, and bridal guidance from Glowup masters.',
                'og_image'         => 'assets/images/Glowup_Logo_Black_White.png',
                'robots'           => 'index, follow',
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'page_key'         => 'contact',
                'page_name'        => 'Contact & Concierge',
                'seo_title'        => 'Contact & Concierge | Glowup Beauty Studio & Academy',
                'meta_description' => 'Get in touch with Glowup Beauty Studio & Academy. Book appointments, enquire about academy admissions, or visit our flagship studio in Madurai.',
                'meta_keywords'    => 'contact salon, studio address, appointment phone, salon madurai',
                'canonical_url'    => '',
                'og_title'         => 'Contact & Concierge | Glowup Beauty Studio & Academy',
                'og_description'   => 'Get in touch with Glowup Beauty Studio & Academy. Book appointments, enquire about academy admissions, or visit our flagship studio in Madurai.',
                'og_image'         => 'assets/images/Glowup_Logo_Black_White.png',
                'robots'           => 'index, follow',
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'page_key'         => 'booking',
                'page_name'        => 'Online Appointment Booking',
                'seo_title'        => 'Online Appointment Booking | Glowup Beauty Studio & Academy',
                'meta_description' => 'Reserve your bespoke beauty, hair, or wellness appointment online at Glowup Beauty Studio & Academy.',
                'meta_keywords'    => 'book salon appointment, schedule appointment, online salon booking',
                'canonical_url'    => '',
                'og_title'         => 'Online Appointment Booking | Glowup Beauty Studio & Academy',
                'og_description'   => 'Reserve your bespoke beauty, hair, or wellness appointment online at Glowup Beauty Studio & Academy.',
                'og_image'         => 'assets/images/Glowup_Logo_Black_White.png',
                'robots'           => 'index, follow',
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'page_key'         => 'profile',
                'page_name'        => 'Patron Profile & Sanctuary Pass',
                'seo_title'        => 'Patron Portal & Sanctuary Pass | Glowup Beauty Studio & Academy',
                'meta_description' => 'Manage your personal appointments, billing history, and membership privileges at Glowup Beauty Studio.',
                'meta_keywords'    => 'customer portal, appointment history, sanctuary pass',
                'canonical_url'    => '',
                'og_title'         => 'Patron Portal & Sanctuary Pass | Glowup Beauty Studio & Academy',
                'og_description'   => 'Manage your personal appointments, billing history, and membership privileges at Glowup Beauty Studio.',
                'og_image'         => 'assets/images/Glowup_Logo_Black_White.png',
                'robots'           => 'noindex, nofollow',
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'page_key'         => 'register',
                'page_name'        => 'Customer Registration',
                'seo_title'        => 'Register | Glowup Beauty Studio & Academy',
                'meta_description' => 'Register your patron membership at Glowup Beauty Studio & Academy.',
                'meta_keywords'    => 'register account, patron signup, member registration',
                'canonical_url'    => '',
                'og_title'         => 'Register | Glowup Beauty Studio & Academy',
                'og_description'   => 'Register your patron membership at Glowup Beauty Studio & Academy.',
                'og_image'         => 'assets/images/Glowup_Logo_Black_White.png',
                'robots'           => 'index, follow',
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'page_key'         => 'login',
                'page_name'        => 'Customer Sign In',
                'seo_title'        => 'Sign In | Glowup Beauty Studio & Academy',
                'meta_description' => 'Access your patron account and appointment dashboard at Glowup Beauty Studio & Academy.',
                'meta_keywords'    => 'customer login, sign in, patron portal',
                'canonical_url'    => '',
                'og_title'         => 'Sign In | Glowup Beauty Studio & Academy',
                'og_description'   => 'Access your patron account and appointment dashboard at Glowup Beauty Studio & Academy.',
                'og_image'         => 'assets/images/Glowup_Logo_Black_White.png',
                'robots'           => 'index, follow',
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
        ];

        $db->table('seo_metadata')->insertBatch($initialPages);
    }

    public function down()
    {
        $this->forge->dropTable('seo_metadata', true);
    }
}
